import { useState } from "react";
import { useToggle, usePrevious, useDebounce, useLocalStorage } from "./hooks.js";
import { LS_KEY } from "../data/info.js";

/**
 * Demo — already complete. It exercises every hook from ./hooks.js:
 *   - useToggle       → toggle-btn / toggle-state
 *   - useDebounce     → deb-input / deb-value  (debounced text)
 *   - usePrevious     → prev-value            (previous debounced value)
 *   - useLocalStorage → ls-input / ls-value   (persisted under LS_KEY)
 *
 * You do NOT edit this file — you implement the hooks in ./hooks.js.
 */
export default function Demo() {
  const [on, toggle] = useToggle(false);

  // A plain React-state input; its value is what we debounce.
  const [text, setText] = useState("");
  const debounced = useDebounce(text, 300);
  const prevDebounced = usePrevious(debounced);

  const [note, setNote] = useLocalStorage(LS_KEY, "");

  return (
    <div className="hb-demo">
      <section className="hb-card">
        <h2 className="hb-h2">useToggle</h2>
        <button className="btn" data-testid="toggle-btn" onClick={() => toggle()}>
          Toggle
        </button>
        <p>
          State: <strong data-testid="toggle-state">{on ? "on" : "off"}</strong>
        </p>
      </section>

      <section className="hb-card">
        <h2 className="hb-h2">useDebounce + usePrevious</h2>
        <input
          className="hb-input"
          data-testid="deb-input"
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Type here…"
        />
        <p>
          Debounced: <strong data-testid="deb-value">{debounced}</strong>
        </p>
        <p>
          Previous:{" "}
          <strong data-testid="prev-value">{prevDebounced ?? ""}</strong>
        </p>
      </section>

      <section className="hb-card">
        <h2 className="hb-h2">useLocalStorage</h2>
        <input
          className="hb-input"
          data-testid="ls-input"
          value={note}
          onChange={(e) => setNote(e.target.value)}
          placeholder="Persisted note…"
        />
        <p>
          Stored: <strong data-testid="ls-value">{note}</strong>
        </p>
      </section>
    </div>
  );
}
